#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="morcilla tests"

set -x

${PREFIX}isort --check --diff --project=morcilla $SOURCE_FILES
${PREFIX}black --check --diff $SOURCE_FILES
#${PREFIX}mypy morcilla
