#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'morcilla.egg-info' ] ; then
    rm -r morcilla.egg-info
fi

find morcilla -type f -name "*.py[co]" -delete
find morcilla -type d -name __pycache__ -delete
